theme: minima

title: Resume

author:
  name: yoshyum

minima:
  social_links:
    - platform: github
    - user_url: "https://github.com/yoshyum"
    - title: GitHub

header_pages:
  - README.md
